/**
 * shipHullGeometry — per-ship procedural hull families for the player spaceship.
 *
 * Every playable ship (src/data/ShipCharacters.ts) owns one hull family here,
 * and each family defines all 10 evolution tiers. A family keeps a
 * recognizable silhouette while every tier visibly changes the craft — new
 * facets, barbs, blades, engines, and pods on top of gradual growth — so
 * evolving reads as "my ship grew teeth", not "I got a different ship".
 *
 * Pure geometry, no Phaser: PlayerSpaceship renders it in-game,
 * WeaponSelectScene renders card previews from it, and the unit suite asserts
 * the invariants (mirror symmetry, closed non-self-intersecting outlines,
 * monotonic tier growth, per-tier visible variation, render-cache fit,
 * per-ship uniqueness).
 *
 * Authoring convention: ships face +x (nose right). Each hull is authored as
 * the NOSE point plus the upper half outline (y < 0, nose → tail) plus an
 * optional tail-center point; the lower half is generated by mirroring, which
 * guarantees symmetry. Details (energy channels, circuit traces, wing edge
 * accents) are generated from the frame's anchors so they always track the
 * silhouette.
 *
 * Tier-gating rhythm shared by the families (t = tier index 0..9):
 *   t1 / t3 / t6 / t8 / t9 — silhouette changes (facets, teeth, blades, tips)
 *   t2 / t4 / t7          — engine layout grows
 *   t5 (+ second pair t9) — energy pods come online
 */

export interface Point2D {
  x: number;
  y: number;
}

export interface CircuitTrace {
  path: Point2D[];
  width: number;
  alpha: number;
}

export interface EnergyChannel {
  path: Point2D[];
  width: number;
  baseAlpha: number;
}

export interface WingEdgeSegment {
  from: Point2D;
  to: Point2D;
}

/** Everything PlayerSpaceship needs to draw one ship at one evolution tier. */
export interface ShipTierGeometry {
  hullOutline: Point2D[];
  cockpit: Point2D[];
  engineNozzles: Point2D[];
  engineNozzleRadius: number;
  wingTipAccents: Point2D[];
  wingTipAccentRadius: number;
  energyPods: Point2D[];
  energyPodRadius: number;
  circuitTraces: CircuitTrace[];
  energyChannels: EnergyChannel[];
  wingEdgeSegments: WingEdgeSegment[];
}

/**
 * Hull family ids. Named after the archetype, not the ship, so a future ship
 * can reuse a family without a confusing name (ShipCharacter.hullId maps
 * roster entries onto these).
 */
export type ShipHullId =
  | 'dart'       // Sparrow — balanced delta dart
  | 'scissor'    // Interceptor — needle nose, forward-swept scissor wings
  | 'ram'        // Dreadnought — broad chisel-prow wedge
  | 'prism'      // Scholar — faceted diamond science vessel with antenna spikes
  | 'bastion'    // Juggernaut — twin-prong ram, slab fortress body
  | 'umbra'      // Void Walker — stealth bat flying-wing, sawtooth trailing edge
  | 'harpoon'    // Boss Hunter — long spinal cannon barrel gunship
  | 'aurora'     // Flawless — elegant fine-faceted crescent wings
  | 'needle'     // Glass Cannon — thin fuselage, oversized X blade array
  | 'mantis'     // Elite Slayer — forked mandible prow predator
  | 'sovereign'; // Apex — crown-spiked multi-wing flagship

export const SHIP_HULL_IDS: readonly ShipHullId[] = [
  'dart', 'scissor', 'ram', 'prism', 'bastion', 'umbra',
  'harpoon', 'aurora', 'needle', 'mantis', 'sovereign',
];

export const SHIP_TIER_COUNT = 10;

/** First tier where energy pods appear on every hull family. */
export const POD_START_TIER = 5;

export const DEFAULT_HULL_ID: ShipHullId = 'dart';

// ---------------------------------------------------------------------------
// Shared authoring helpers
// ---------------------------------------------------------------------------

/** Overall size multiplier per evolution tier (10 steps, ~+7% each). */
const TIER_SCALE = [1.0, 1.07, 1.14, 1.21, 1.28, 1.35, 1.42, 1.48, 1.55, 1.62];

const P = (x: number, y: number): Point2D => ({ x, y });

/** Pick the last stage whose gate tier is <= t (stages sorted ascending). */
function pick<T>(tier: number, stages: [number, T][]): T {
  let result = stages[0][1];
  for (const [gate, value] of stages) {
    if (tier >= gate) result = value;
  }
  return result;
}

/**
 * Frame authored per hull per tier — everything else (mirroring, traces,
 * channels, edge accents) is derived from it.
 */
interface HullFrame {
  nose: Point2D;
  /** Upper half outline, nose → tail, all y < 0. Mirrored automatically. */
  upperHull: Point2D[];
  /** Optional centerline tail point (omit for a flat/open notched tail). */
  tailCenter?: Point2D;
  cockpit: Point2D[];
  /** Full engine set (author ± pairs explicitly via enginePair). */
  engines: Point2D[];
  engineNozzleRadius: number;
  /** Upper-half accent anchors; mirrored automatically. */
  wingTips: Point2D[];
  wingTipAccentRadius: number;
  /** Upper-half pod anchors; mirrored automatically. */
  pods: Point2D[];
  energyPodRadius: number;
}

/** Mirror upper-half anchors across the x axis (y=0 anchors stay single). */
function mirrorAnchors(upper: Point2D[]): Point2D[] {
  const result: Point2D[] = [];
  for (const point of upper) {
    result.push(point);
    if (point.y !== 0) result.push(P(point.x, -point.y));
  }
  return result;
}

/** Symmetric engine pair helper. */
function enginePair(x: number, y: number): Point2D[] {
  return [P(x, -y), P(x, y)];
}

/** Six-point hex cockpit (front point → upper edge → back point → lower edge). */
function hexCockpit(frontX: number, backX: number, halfWidth: number): Point2D[] {
  const length = frontX - backX;
  const upperFrontX = backX + length * 0.65;
  const upperBackX = backX + length * 0.22;
  return [
    P(frontX, 0),
    P(upperFrontX, -halfWidth),
    P(upperBackX, -halfWidth),
    P(backX, 0),
    P(upperBackX, halfWidth),
    P(upperFrontX, halfWidth),
  ];
}

/** Four-point diamond cockpit. */
function diamondCockpit(frontX: number, backX: number, halfWidth: number): Point2D[] {
  const midX = (frontX + backX) / 2;
  return [P(frontX, 0), P(midX, -halfWidth), P(backX, 0), P(midX, halfWidth)];
}

/** Wide low trapezoid visor (heavy ships — bridge slit, not a bubble). */
function visorCockpit(frontX: number, backX: number, halfWidth: number): Point2D[] {
  const length = frontX - backX;
  return [
    P(frontX, -halfWidth * 0.45),
    P(backX + length * 0.15, -halfWidth),
    P(backX, -halfWidth * 0.55),
    P(backX, halfWidth * 0.55),
    P(backX + length * 0.15, halfWidth),
    P(frontX, halfWidth * 0.45),
  ];
}

// ---------------------------------------------------------------------------
// Hull family builders — one per playable ship archetype
// ---------------------------------------------------------------------------
//
// Each builder receives the tier index (0..9) and returns a HullFrame.
// `k` scales the whole craft per tier; `w` widens wings faster than the hull
// so higher tiers read more aggressive, not just bigger. Vertices gated on
// tier grow new facets/teeth/blades at evolution breakpoints (see the rhythm
// note in the module header).

type HullBuilder = (tier: number) => HullFrame;

const buildDart: HullBuilder = (t) => {
  const k = TIER_SCALE[t];
  const w = 1 + t * 0.036;
  const p = (x: number, y: number) => P(x * k, y * k);
  const wing = (x: number, y: number) => P(x * k, y * k * w);

  const nose = p(t >= 9 ? 24 : 22, 0);                // t9: lance nose
  const upperHull: Point2D[] = [p(13, -2.6)];
  if (t >= 1) upperHull.push(p(9, -3.2), p(8, -4.4)); // t1: leading-edge step
  upperHull.push(p(4, -4.6), p(-3, -5));
  if (t >= 3) upperHull.push(wing(-7, -8));           // t3: mid-wing facet
  upperHull.push(wing(-11, -10.5));                   // main swept tip
  if (t >= 8) upperHull.push(wing(-15.5, -12.5));     // t8: blade extension
  if (t >= 9) upperHull.push(wing(-12, -9.5));        // t9: blade serration
  upperHull.push(p(-8, -5));
  if (t >= 6) upperHull.push(p(-12, -5.4));           // t6: tail fin blade
  upperHull.push(p(-12, -2.4));

  const engines = pick<Point2D[]>(t, [
    [0, [P(-7 * k, 0)]],
    [2, [P(-7.5 * k, 0), ...enginePair(-7.5 * k, 2.4 * k)]],
    [4, [P(-8 * k, 0), ...enginePair(-8 * k, 3.2 * k)]],
    [7, [P(-9 * k, 0), ...enginePair(-9 * k, 3.6 * k), ...enginePair(-8 * k, 1.8 * k)]],
  ]);

  const pods: Point2D[] = [];
  if (t >= 5) pods.push(wing(-5, -6.8));
  if (t >= 9) pods.push(wing(-1, -5.6));

  return {
    nose,
    upperHull,
    tailCenter: p(-9, 0),
    cockpit: hexCockpit(12 * k, -1 * k, 2.1 * k),
    engines,
    engineNozzleRadius: (1.9 + t * 0.11) * k * 0.9,
    wingTips: [t >= 8 ? wing(-15.5, -12.5) : wing(-11, -10.5)],
    wingTipAccentRadius: 1.0 + t * 0.13,
    pods,
    energyPodRadius: 1.8 + Math.max(0, t - POD_START_TIER) * 0.22,
  };
};

const buildScissor: HullBuilder = (t) => {
  const k = TIER_SCALE[t];
  const w = 1 + t * 0.04;
  const p = (x: number, y: number) => P(x * k, y * k);
  const wing = (x: number, y: number) => P(x * k, y * k * w);

  const mainTip = t >= 9 ? wing(12.5, -11) : wing(11, -9.5);
  const upperHull: Point2D[] = [p(14, -2)];
  if (t >= 1) upperHull.push(p(10, -3.6), p(8, -2.6)); // t1: canard bump
  upperHull.push(p(6, -2.8));
  upperHull.push(mainTip);                             // forward-swept scissor tip
  if (t >= 3) upperHull.push(wing(4, -11));            // t3: second forward tooth
  upperHull.push(wing(-3, -7.5));
  if (t >= 6) upperHull.push(p(-1, -4.9));             // t6: trailing notch tooth
  upperHull.push(p(-7, -3.4));
  if (t >= 8) upperHull.push(wing(-11, -8.5));         // t8: rear scissor blade
  upperHull.push(p(-13, -5.5));                        // tail fin

  const engines = pick<Point2D[]>(t, [
    [0, [P(-8 * k, 0)]],
    [2, [P(-9 * k, 0), ...enginePair(-8 * k, 2.2 * k)]],
    [4, [P(-9.5 * k, 0), ...enginePair(-8.5 * k, 2.8 * k)]],
    [7, [P(-9.5 * k, 0), ...enginePair(-8.5 * k, 3.4 * k)]],
  ]);

  const pods: Point2D[] = [];
  if (t >= 5) pods.push(wing(0, -8.6));
  if (t >= 9) pods.push(wing(4, -6.2));

  return {
    nose: p(27, 0),
    upperHull,
    tailCenter: p(-10, 0),
    cockpit: hexCockpit(15 * k, 3 * k, 1.7 * k),
    engines,
    engineNozzleRadius: (1.7 + t * 0.1) * k * 0.9,
    wingTips: t >= 3 ? [mainTip, wing(4, -11)] : [mainTip],
    wingTipAccentRadius: 0.9 + t * 0.12,
    pods,
    energyPodRadius: 1.6 + Math.max(0, t - POD_START_TIER) * 0.22,
  };
};

const buildRam: HullBuilder = (t) => {
  const k = TIER_SCALE[t];
  const w = 1 + t * 0.031;
  const p = (x: number, y: number) => P(x * k, y * k);
  const wing = (x: number, y: number) => P(x * k, y * k * w);

  const upperHull: Point2D[] = [t >= 9 ? p(18, -5.8) : p(17, -5.2)]; // t9: harder prow
  if (t >= 1) upperHull.push(p(13, -6.2), p(12, -7.2)); // t1: prow serration
  upperHull.push(p(7, -8));
  if (t >= 3) upperHull.push(wing(1, -10.6));           // t3: shoulder ridge
  upperHull.push(wing(-2, -9.2), wing(-9, -13));        // stub wing
  if (t >= 8) upperHull.push(wing(-13, -15.5));         // t8: heavy wing extension
  upperHull.push(p(-6, -7));
  if (t >= 6) upperHull.push(p(-11, -10.4));            // t6: side armor spike
  upperHull.push(p(-13, -8.6));                         // rear plate
  if (t >= 9) upperHull.push(p(-14.5, -5.5));           // t9: aft armor step

  const engines = pick<Point2D[]>(t, [
    [0, enginePair(-8 * k, 3 * k)],
    [2, enginePair(-8.5 * k, 3.6 * k)],
    [4, [P(-9 * k, 0), ...enginePair(-9 * k, 4.2 * k)]],
    [7, [...enginePair(-9.5 * k, 1.8 * k), ...enginePair(-9.5 * k, 4.8 * k)]],
    [9, [P(-10 * k, 0), ...enginePair(-10 * k, 2.4 * k), ...enginePair(-10 * k, 5.2 * k)]],
  ]);

  const pods: Point2D[] = [];
  if (t >= 5) pods.push(wing(-2, -10.8));
  if (t >= 9) pods.push(p(4, -8.6));

  return {
    nose: p(21, 0),
    upperHull,
    tailCenter: p(-11, 0),
    cockpit: visorCockpit(11 * k, 1 * k, 3 * k),
    engines,
    engineNozzleRadius: (2.3 + t * 0.12) * k * 0.9,
    wingTips: [t >= 8 ? wing(-13, -15.5) : wing(-9, -13)],
    wingTipAccentRadius: 1.2 + t * 0.14,
    pods,
    energyPodRadius: 2.1 + Math.max(0, t - POD_START_TIER) * 0.22,
  };
};

const buildPrism: HullBuilder = (t) => {
  const k = TIER_SCALE[t];
  const w = 1 + t * 0.044;
  const p = (x: number, y: number) => P(x * k, y * k);
  const wing = (x: number, y: number) => P(x * k, y * k * w);

  const upperHull: Point2D[] = [p(9, -5.6)];
  if (t >= 1) upperHull.push(p(5, -8.2));              // t1: crystal facet
  upperHull.push(p(0, -7.4));
  upperHull.push(wing(-4, t >= 9 ? -15 : -13.5));      // primary antenna (t9: longer)
  if (t >= 3) upperHull.push(wing(-7, -8.6), wing(-10, -12)); // t3: second antenna
  upperHull.push(p(-6.5, -7.2));
  if (t >= 6) upperHull.push(p(-10, -8.4));            // t6: lower sensor vane
  if (t >= 8) upperHull.push(wing(-12, -9.5));         // t8: rear vane
  upperHull.push(p(-13, -4.6));

  const engines = pick<Point2D[]>(t, [
    [0, [P(-12 * k, 0)]],
    [2, [P(-13 * k, 0)]],
    [4, [P(-13 * k, 0), ...enginePair(-11.5 * k, 3.2 * k)]],
    [7, [P(-13 * k, 0), ...enginePair(-11.5 * k, 3.8 * k)]],
  ]);

  const pods: Point2D[] = [];
  if (t >= 5) pods.push(wing(-1.5, -9.8));
  if (t >= 9) pods.push(p(-8, -6.2));

  return {
    nose: p(20, 0),
    upperHull,
    tailCenter: p(-15, 0),
    cockpit: diamondCockpit(13 * k, 3 * k, 2.4 * k),
    engines,
    engineNozzleRadius: (1.8 + t * 0.11) * k * 0.9,
    wingTips: t >= 3
      ? [wing(-4, t >= 9 ? -15 : -13.5), wing(-10, -12)]
      : [wing(-4, t >= 9 ? -15 : -13.5)],
    wingTipAccentRadius: 1.1 + t * 0.13,
    pods,
    energyPodRadius: 1.9 + Math.max(0, t - POD_START_TIER) * 0.22,
  };
};

const buildBastion: HullBuilder = (t) => {
  const k = TIER_SCALE[t];
  const w = 1 + t * 0.027;
  const p = (x: number, y: number) => P(x * k, y * k);
  const wing = (x: number, y: number) => P(x * k, y * k * w);

  const upperHull: Point2D[] = [p(23, -6.2)];          // forward ram prong
  if (t >= 3) upperHull.push(p(19, -3.6), p(21, -7.4)); // t3: serrated prong notch
  upperHull.push(p(16, -8.8));
  if (t >= 9) upperHull.push(p(14, -11));              // t9: second forward tusk
  upperHull.push(p(4, -10.4));
  if (t >= 1) upperHull.push(p(0, -11.4));             // t1: hull armor ridge
  upperHull.push(wing(-5, -14.2));                     // shoulder wing
  if (t >= 8) upperHull.push(wing(-9, -16.8));         // t8: bulwark blade
  upperHull.push(p(-9, -8.4));
  if (t >= 6) upperHull.push(p(-11, -11.6));           // t6: side bulwark spike
  upperHull.push(p(-15, -10.2));                       // rear plate

  const engines = pick<Point2D[]>(t, [
    [0, enginePair(-9 * k, 3.4 * k)],
    [2, enginePair(-9.5 * k, 4 * k)],
    [4, [P(-10 * k, 0), ...enginePair(-10 * k, 4.6 * k)]],
    [7, [...enginePair(-10.5 * k, 2 * k), ...enginePair(-10.5 * k, 5 * k)]],
    [9, [P(-10.5 * k, 0), ...enginePair(-10.5 * k, 2.4 * k), ...enginePair(-10.5 * k, 5.4 * k)]],
  ]);

  const pods: Point2D[] = [];
  if (t >= 5) pods.push(wing(0, -11.6));
  if (t >= 9) pods.push(p(8, -8.6));

  return {
    nose: p(15, 0),
    upperHull,
    tailCenter: p(-12, 0),
    cockpit: visorCockpit(10 * k, 0, 3.4 * k),
    engines,
    engineNozzleRadius: (2.5 + t * 0.13) * k * 0.9,
    wingTips: [p(23, -6.2), t >= 8 ? wing(-9, -16.8) : wing(-5, -14.2)],
    wingTipAccentRadius: 1.3 + t * 0.13,
    pods,
    energyPodRadius: 2.2 + Math.max(0, t - POD_START_TIER) * 0.22,
  };
};

const buildUmbra: HullBuilder = (t) => {
  const k = TIER_SCALE[t];
  const w = 1 + t * 0.044;
  const p = (x: number, y: number) => P(x * k, y * k);
  const wing = (x: number, y: number) => P(x * k, y * k * w);

  const upperHull: Point2D[] = [p(10, -4.2)];
  if (t >= 1) upperHull.push(p(5, -5.4), p(4, -6.8));  // t1: leading-edge facet
  upperHull.push(p(-1, -8.2));
  if (t >= 9) upperHull.push(wing(-4, -10.6));         // t9: fore-wing facet
  upperHull.push(wing(-7, -15.5));                     // bat wingtip
  if (t >= 8) upperHull.push(wing(-11, -18));          // t8: deep talon tip
  if (t >= 6) upperHull.push(wing(-9.5, -13.4));       // t6: talon barb
  upperHull.push(wing(-5, -10.5), wing(-9, -8));       // sawtooth 1
  if (t >= 3) upperHull.push(p(-6.5, -6.2), p(-10.5, -4.8)); // t3: sawtooth 2
  upperHull.push(p(-6, -3.2), p(-10, -2));             // sawtooth 3

  const engines = pick<Point2D[]>(t, [
    [0, enginePair(-6 * k, 2.6 * k)],
    [2, enginePair(-6.5 * k, 3.2 * k)],
    [4, [...enginePair(-7 * k, 2.2 * k), ...enginePair(-6 * k, 4.6 * k)]],
    [7, [...enginePair(-7 * k, 2.2 * k), ...enginePair(-6 * k, 5.2 * k)]],
  ]);

  const pods: Point2D[] = [];
  if (t >= 5) pods.push(wing(-3, -11));
  if (t >= 9) pods.push(p(1, -7.2));

  return {
    nose: p(23, 0),
    upperHull,
    tailCenter: p(-7.5, 0),
    cockpit: hexCockpit(14 * k, 5 * k, 1.4 * k),
    engines,
    engineNozzleRadius: (1.8 + t * 0.1) * k * 0.9,
    wingTips: [t >= 8 ? wing(-11, -18) : wing(-7, -15.5)],
    wingTipAccentRadius: 1.0 + t * 0.13,
    pods,
    energyPodRadius: 1.8 + Math.max(0, t - POD_START_TIER) * 0.22,
  };
};

const buildHarpoon: HullBuilder = (t) => {
  const k = TIER_SCALE[t];
  const w = 1 + t * 0.036;
  const p = (x: number, y: number) => P(x * k, y * k);
  const wing = (x: number, y: number) => P(x * k, y * k * w);

  const noseX = t >= 9 ? 33 : 31;                      // t9: extended muzzle
  const upperHull: Point2D[] = [p(24, -1.6)];
  if (t >= 1) upperHull.push(p(20, -2.4), p(19, -1.7)); // t1: barrel band
  upperHull.push(p(14, -1.9));
  if (t >= 3) upperHull.push(p(16, -3.8), p(12, -3));   // t3: muzzle brake vanes
  upperHull.push(p(11, -4.6), p(2, -7));                // barrel shoulder
  upperHull.push(wing(-4, -12.8));                      // cannon pod wing
  if (t >= 8) upperHull.push(wing(-8, -15.2));          // t8: heavy pod extension
  upperHull.push(p(-8, -7.6));
  if (t >= 6) upperHull.push(p(-11, -8.8));             // t6: mid stabilizer fin
  upperHull.push(t >= 9 ? p(-15, -5.8) : p(-14, -5));   // tail fin (t9: deeper)

  const engines = pick<Point2D[]>(t, [
    [0, [P(-9 * k, 0)]],
    [2, [P(-9.5 * k, 0), ...enginePair(-8.5 * k, 2.6 * k)]],
    [4, [P(-10 * k, 0), ...enginePair(-9 * k, 3.2 * k)]],
    [7, [P(-10 * k, 0), ...enginePair(-9 * k, 3.8 * k)]],
  ]);

  const pods: Point2D[] = [];
  if (t >= 5) pods.push(wing(-2, -9.4));
  if (t >= 9) pods.push(p(3, -6.4));

  return {
    nose: p(noseX, 0),
    upperHull,
    tailCenter: p(-11, 0),
    cockpit: hexCockpit(9 * k, -2 * k, 2.2 * k),
    engines,
    engineNozzleRadius: (1.9 + t * 0.11) * k * 0.9,
    wingTips: [p(noseX - 1.5, 0), t >= 8 ? wing(-8, -15.2) : wing(-4, -12.8)],
    wingTipAccentRadius: 0.9 + t * 0.12,
    pods,
    energyPodRadius: 2.0 + Math.max(0, t - POD_START_TIER) * 0.22,
  };
};

const buildAurora: HullBuilder = (t) => {
  const k = TIER_SCALE[t];
  const w = 1 + t * 0.04;
  const p = (x: number, y: number) => P(x * k, y * k);
  const wing = (x: number, y: number) => P(x * k, y * k * w);

  const upperHull: Point2D[] = [p(13, -2.2)];
  if (t >= 1) upperHull.push(p(8, -3.6));              // t1: fairing facet
  upperHull.push(p(2, -4.4));
  if (t >= 3) upperHull.push(wing(-2, -6.6));          // t3: crescent facet
  upperHull.push(wing(-6, -8.8));
  if (t >= 6) upperHull.push(wing(-9, -11.4));         // t6: finer crescent sweep
  upperHull.push(wing(-12, -13.5));
  if (t >= 8) upperHull.push(wing(-16, -16));          // t8: grand wing extension
  if (t >= 9) upperHull.push(wing(-14.5, -12.4));      // t9: trailing ribbon facet
  upperHull.push(wing(-13, -9.5), p(-10, -5), p(-14, -2.2));

  const engines = pick<Point2D[]>(t, [
    [0, [P(-8 * k, 0)]],
    [2, enginePair(-8.5 * k, 2.2 * k)],
    [4, [P(-9 * k, 0), ...enginePair(-9 * k, 3 * k)]],
    [7, [P(-9.5 * k, 0), ...enginePair(-9.5 * k, 3.6 * k)]],
  ]);

  const pods: Point2D[] = [];
  if (t >= 5) pods.push(wing(-7, -10.2));
  if (t >= 9) pods.push(p(-1, -5.4));

  return {
    nose: p(25, 0),
    upperHull,
    tailCenter: p(t >= 9 ? -12 : -11, 0),
    cockpit: hexCockpit(14 * k, 2 * k, 1.9 * k),
    engines,
    engineNozzleRadius: (1.8 + t * 0.1) * k * 0.9,
    wingTips: [t >= 8 ? wing(-16, -16) : wing(-12, -13.5)],
    wingTipAccentRadius: 1.0 + t * 0.13,
    pods,
    energyPodRadius: 1.8 + Math.max(0, t - POD_START_TIER) * 0.22,
  };
};

const buildNeedle: HullBuilder = (t) => {
  const k = TIER_SCALE[t];
  const w = 1 + t * 0.044;
  const p = (x: number, y: number) => P(x * k, y * k);
  const wing = (x: number, y: number) => P(x * k, y * k * w);

  const forwardBlade = t >= 9 ? wing(16.5, -11) : wing(15, -9.8);
  const upperHull: Point2D[] = [p(18, -1.6)];
  if (t >= 1) upperHull.push(p(14, -2.6), p(13, -1.8)); // t1: needle collar
  upperHull.push(p(8, -2.8));
  upperHull.push(forwardBlade);                         // forward blade
  if (t >= 3) upperHull.push(wing(8, -11.4));           // t3: blade barb
  upperHull.push(wing(2, -7.6), p(-4, -4.2));
  if (t >= 6) upperHull.push(p(-5, -7.4));              // t6: mid spar kink
  upperHull.push(wing(-10, -11.8));                     // rear blade
  if (t >= 8) upperHull.push(wing(-14, -13.6));         // t8: rear blade extension
  upperHull.push(p(-8, -4.8));

  const engines = pick<Point2D[]>(t, [
    [0, [P(-9 * k, 0)]],
    [2, [P(-9.5 * k, 0), ...enginePair(-8 * k, 2 * k)]],
    [4, [P(-10 * k, 0), ...enginePair(-8.5 * k, 2.6 * k)]],
    [7, [P(-10 * k, 0), ...enginePair(-8.5 * k, 3.2 * k)]],
  ]);

  const pods: Point2D[] = [];
  if (t >= 5) pods.push(wing(4, -8.8));
  if (t >= 9) pods.push(p(-2, -5.6));

  return {
    nose: p(29, 0),
    upperHull,
    tailCenter: p(-11, 0),
    cockpit: hexCockpit(13 * k, 3 * k, 1.3 * k),
    engines,
    engineNozzleRadius: (1.6 + t * 0.1) * k * 0.9,
    wingTips: t >= 3 ? [forwardBlade, wing(-10, -11.8)] : [forwardBlade],
    wingTipAccentRadius: 0.9 + t * 0.13,
    pods,
    energyPodRadius: 1.6 + Math.max(0, t - POD_START_TIER) * 0.22,
  };
};

const buildMantis: HullBuilder = (t) => {
  const k = TIER_SCALE[t];
  const w = 1 + t * 0.036;
  const p = (x: number, y: number) => P(x * k, y * k);
  const wing = (x: number, y: number) => P(x * k, y * k * w);

  const mandibleTip = t >= 9 ? wing(27, -5) : wing(25, -4.6);
  const upperHull: Point2D[] = [mandibleTip];          // mandible tip
  if (t >= 1) upperHull.push(p(21, -5), p(22, -6.6));  // t1: mandible serration
  if (t >= 3) upperHull.push(wing(21, -8.2));          // t3: mandible barb
  upperHull.push(wing(19, -7.6), p(8, -6.4), p(-1, -8.2));
  if (t >= 6) upperHull.push(p(-2, -11));              // t6: thorax spike
  upperHull.push(wing(-9, -12.6));                     // swept hind wing
  if (t >= 8) upperHull.push(wing(-13, -15));          // t8: hind wing talon
  upperHull.push(p(-7, -6.6), p(-13, -3.8));

  const engines = pick<Point2D[]>(t, [
    [0, [P(-8 * k, 0)]],
    [2, enginePair(-8.5 * k, 2.4 * k)],
    [4, [P(-9 * k, 0), ...enginePair(-9 * k, 3.2 * k)]],
    [7, [P(-9.5 * k, 0), ...enginePair(-9.5 * k, 3.8 * k)]],
  ]);

  const pods: Point2D[] = [];
  if (t >= 5) pods.push(wing(-4, -9.8));
  if (t >= 9) pods.push(p(2, -6.8));

  return {
    nose: p(17, 0),
    upperHull,
    tailCenter: p(-10, 0),
    cockpit: hexCockpit(11 * k, 0, 2 * k),
    engines,
    engineNozzleRadius: (1.8 + t * 0.11) * k * 0.9,
    wingTips: [mandibleTip, t >= 8 ? wing(-13, -15) : wing(-9, -12.6)],
    wingTipAccentRadius: 1.0 + t * 0.13,
    pods,
    energyPodRadius: 1.9 + Math.max(0, t - POD_START_TIER) * 0.22,
  };
};

const buildSovereign: HullBuilder = (t) => {
  const k = TIER_SCALE[t];
  const w = 1 + t * 0.036;
  const p = (x: number, y: number) => P(x * k, y * k);
  const wing = (x: number, y: number) => P(x * k, y * k * w);

  const upperHull: Point2D[] = [p(14, -4.4)];          // (t9 gains a lance nose)
  if (t >= 1) upperHull.push(p(10, -6.6));             // t1: crown step facet
  upperHull.push(wing(4, -12.5));                      // crown spike
  upperHull.push(p(0, -7.8));
  if (t >= 3) upperHull.push(wing(-5, -13.8), p(-4, -8.6)); // t3: second crown spike
  upperHull.push(wing(-13, -17.5));                    // grand swept wing
  if (t >= 8) upperHull.push(wing(-17, -20));          // t8: apex wing talon
  if (t >= 6) upperHull.push(wing(-10.5, -13.8));      // t6: wing serration
  upperHull.push(p(-10, -9));
  upperHull.push(wing(-19, -12.4));                    // rear blade
  if (t >= 9) upperHull.push(p(-16.5, -8.2));          // t9: rear blade serration
  upperHull.push(p(-14, -4.6));

  const engines = pick<Point2D[]>(t, [
    [0, [P(-13 * k, 0), ...enginePair(-12 * k, 3 * k)]],
    [2, [P(-13.5 * k, 0), ...enginePair(-12.5 * k, 3.6 * k)]],
    [4, [P(-14 * k, 0), ...enginePair(-13 * k, 2.2 * k), ...enginePair(-12.5 * k, 4.4 * k)]],
    [7, [P(-14 * k, 0), ...enginePair(-13 * k, 2.2 * k), ...enginePair(-12.5 * k, 5 * k)]],
  ]);

  const pods: Point2D[] = [];
  if (t >= 5) pods.push(wing(-8, -12.2));
  if (t >= 9) pods.push(p(1, -9.4));

  return {
    nose: p(t >= 9 ? 29 : 27, 0),
    upperHull,
    tailCenter: p(-16, 0),
    cockpit: diamondCockpit(16 * k, 4 * k, 2.6 * k),
    engines,
    engineNozzleRadius: (2.0 + t * 0.12) * k * 0.9,
    wingTips: t >= 3
      ? [wing(4, -12.5), t >= 8 ? wing(-17, -20) : wing(-13, -17.5), wing(-19, -12.4)]
      : [wing(4, -12.5), wing(-13, -17.5)],
    wingTipAccentRadius: 1.1 + t * 0.14,
    pods,
    energyPodRadius: 2.0 + Math.max(0, t - POD_START_TIER) * 0.22,
  };
};

const HULL_BUILDERS: Record<ShipHullId, HullBuilder> = {
  dart: buildDart,
  scissor: buildScissor,
  ram: buildRam,
  prism: buildPrism,
  bastion: buildBastion,
  umbra: buildUmbra,
  harpoon: buildHarpoon,
  aurora: buildAurora,
  needle: buildNeedle,
  mantis: buildMantis,
  sovereign: buildSovereign,
};

// ---------------------------------------------------------------------------
// Derived details — generated from the frame so they always fit the hull
// ---------------------------------------------------------------------------

function buildOutline(frame: HullFrame): Point2D[] {
  const lower = frame.upperHull
    .slice()
    .reverse()
    .map((point) => P(point.x, -point.y));
  return frame.tailCenter
    ? [frame.nose, ...frame.upperHull, frame.tailCenter, ...lower]
    : [frame.nose, ...frame.upperHull, ...lower];
}

function cockpitBounds(cockpit: Point2D[]): { frontX: number; backX: number; halfWidth: number } {
  let frontX = -Infinity;
  let backX = Infinity;
  let halfWidth = 0;
  for (const point of cockpit) {
    if (point.x > frontX) frontX = point.x;
    if (point.x < backX) backX = point.x;
    const absY = Math.abs(point.y);
    if (absY > halfWidth) halfWidth = absY;
  }
  return { frontX, backX, halfWidth };
}

function buildEnergyChannels(frame: HullFrame, tier: number): EnergyChannel[] {
  const channels: EnergyChannel[] = [];
  const { frontX, backX } = cockpitBounds(frame.cockpit);

  // Central spine: cockpit → rearmost engine (or tail).
  let rearX = frame.tailCenter ? frame.tailCenter.x * 0.9 : backX - 4;
  for (const engine of frame.engines) {
    if (engine.x < rearX) rearX = engine.x;
  }
  channels.push({
    path: [P(frontX * 0.85, 0), P(rearX, 0)],
    width: 1.2 + tier * 0.035,
    baseAlpha: 0.5 + tier * 0.011,
  });

  // Side conduits: cockpit rear → each off-axis engine (dedup mirrored pairs).
  const seen = new Set<string>();
  for (const engine of frame.engines) {
    if (engine.y === 0) continue;
    const key = `${engine.x.toFixed(2)}:${Math.abs(engine.y).toFixed(2)}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const sign = engine.y < 0 ? -1 : 1;
    for (const side of [sign, -sign]) {
      channels.push({
        path: [
          P(backX, 0),
          P((backX + engine.x) / 2, Math.abs(engine.y) * 0.7 * side),
          P(engine.x, Math.abs(engine.y) * side),
        ],
        width: 1.0,
        baseAlpha: 0.45,
      });
    }
    if (channels.length >= 5) break; // spine + 2 mirrored pairs max
  }

  return channels;
}

function buildCircuitTraces(frame: HullFrame, tier: number): CircuitTrace[] {
  const traces: CircuitTrace[] = [];
  const alpha = 0.3 + tier * 0.013;

  // Wing traces: diagonal circuit lines chasing each accent anchor.
  for (const tip of frame.wingTips) {
    if (tip.y === 0) continue;
    for (const sign of [1, -1]) {
      traces.push({
        path: [
          P(tip.x * 0.2, tip.y * 0.3 * sign),
          P(tip.x * 0.6, tip.y * 0.62 * sign),
          P(tip.x * 0.9, tip.y * 0.88 * sign),
        ],
        width: 0.6,
        alpha,
      });
    }
  }

  // Pod feed lines.
  for (const pod of frame.pods) {
    for (const sign of [1, -1]) {
      traces.push({
        path: [P(pod.x * 0.4, pod.y * 0.4 * sign), P(pod.x, pod.y * sign)],
        width: 0.7,
        alpha: 0.4,
      });
    }
  }

  // Late tiers: parallel fuselage circuit rails.
  if (tier >= 6) {
    const { frontX, halfWidth } = cockpitBounds(frame.cockpit);
    const railY = Math.max(1.4, halfWidth * 0.8);
    const rearX = (frame.tailCenter ? frame.tailCenter.x : -frontX) * 0.6;
    for (const sign of [1, -1]) {
      traces.push({
        path: [P(frontX * 0.55, railY * sign), P(rearX, railY * sign)],
        width: 0.4,
        alpha: 0.2,
      });
    }
  }

  return traces;
}

function buildWingEdgeSegments(frame: HullFrame, tier: number): WingEdgeSegment[] {
  if (tier === 0) return [];

  // Longest upper-hull edges are the leading edges — accent their midsections.
  const vertices = [frame.nose, ...frame.upperHull];
  const edges: { from: Point2D; to: Point2D; length: number }[] = [];
  for (let i = 1; i < vertices.length; i++) {
    const from = vertices[i - 1];
    const to = vertices[i];
    const length = Math.hypot(to.x - from.x, to.y - from.y);
    edges.push({ from, to, length });
  }
  edges.sort((a, b) => b.length - a.length);

  // 1 accent pair at t1-3, 2 at t4-6, 3 at t7-9.
  const count = Math.min(1 + Math.floor((tier - 1) / 3), 3, edges.length);
  const segments: WingEdgeSegment[] = [];
  for (let i = 0; i < count; i++) {
    const edge = edges[i];
    for (const sign of [1, -1]) {
      // Midsection (25%..75%), pulled 8% toward the origin (inset from the rim).
      const at = (fraction: number): Point2D => P(
        (edge.from.x + (edge.to.x - edge.from.x) * fraction) * 0.92,
        (edge.from.y + (edge.to.y - edge.from.y) * fraction) * 0.92 * sign
      );
      segments.push({ from: at(0.25), to: at(0.75) });
    }
  }
  return segments;
}

function finalizeGeometry(frame: HullFrame, tier: number): ShipTierGeometry {
  return {
    hullOutline: buildOutline(frame),
    cockpit: frame.cockpit,
    engineNozzles: frame.engines,
    engineNozzleRadius: frame.engineNozzleRadius,
    wingTipAccents: mirrorAnchors(frame.wingTips),
    wingTipAccentRadius: frame.wingTipAccentRadius,
    energyPods: mirrorAnchors(frame.pods),
    energyPodRadius: frame.pods.length > 0 ? frame.energyPodRadius : 0,
    circuitTraces: buildCircuitTraces(frame, tier),
    energyChannels: buildEnergyChannels(frame, tier),
    wingEdgeSegments: buildWingEdgeSegments(frame, tier),
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

const geometryCache = new Map<string, ShipTierGeometry>();

/**
 * Resolve the geometry for a hull family at an evolution tier (0..9).
 * Unknown hull ids fall back to the default dart so a stale save can never
 * render nothing. Results are cached (pure data, safe to share).
 */
export function getShipTierGeometry(hullId: string, tierIndex: number): ShipTierGeometry {
  const resolvedHullId: ShipHullId =
    (SHIP_HULL_IDS as readonly string[]).includes(hullId) ? (hullId as ShipHullId) : DEFAULT_HULL_ID;
  const clampedTier = Math.max(0, Math.min(SHIP_TIER_COUNT - 1, Math.floor(tierIndex)));

  const cacheKey = `${resolvedHullId}:${clampedTier}`;
  let geometry = geometryCache.get(cacheKey);
  if (!geometry) {
    geometry = finalizeGeometry(HULL_BUILDERS[resolvedHullId](clampedTier), clampedTier);
    geometryCache.set(cacheKey, geometry);
  }
  return geometry;
}

/** Axis-aligned bounds of an outline (preview scaling, cache-fit tests). */
export function getHullBounds(outline: Point2D[]): {
  minX: number; maxX: number; minY: number; maxY: number;
} {
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (const point of outline) {
    if (point.x < minX) minX = point.x;
    if (point.x > maxX) maxX = point.x;
    if (point.y < minY) minY = point.y;
    if (point.y > maxY) maxY = point.y;
  }
  return { minX, maxX, minY, maxY };
}
